service: cug-landing-page
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
