# Deploy to Google App Engine
name: CI
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.APP_ENGINE_PROJECT_NAME }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCLOUD_CREDENTIALS }}
